services:
  auth:
    container_name: srv-auth
    build:
      context: ../auth
    volumes:
      - pub_key:/rsa/pub
      - priv_key:/rsa/priv
    env_file: .env
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.auth.rule=Host(`auth.${DOMAIN}`)
      - traefik.http.routers.auth.entrypoints=web

  auth_conf:
    container_name: conf-auth
    build:
      context: ../auth
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    entrypoint: [php, app/ice, dbup, "--schema={perfiles,[!t]*}"]
    restart: on-failure
volumes:
  pub_key:
  priv_key:
