services:
  db:
    container_name: srv-db
    image: postgres:14.1-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: caresoft
    restart: always
    healthcheck:
      test: [CMD-SHELL, pg_isready]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
volumes:
  pg_data: