services:
  geo:
    container_name: srv-geo
    build:
      context: ../geo
    volumes:
      - pub_key:/rsa/pub:ro
    env_file: .env
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.geo.rule=Host(`geo.${DOMAIN}`)
      - traefik.http.routers.geo.entrypoints=web

  geo_conf:
    container_name: conf-geo
    build:
      context: ../geo
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    entrypoint: [php, app/ice, dbup, "--schema=[!t]*"]
    restart: on-failure
