services:
  mq:
    container_name: srv-mq
    image: rabbitmq:3.13.6-management-alpine
    ports:
      - 8072:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${MQ_PASSWORD}
