services:
  pgaudit:
    container_name: srv-pgaudit
    build:
      context: ../pgaudit-api
    volumes:
      - pub_key:/rsa/pub:ro
    env_file: .env
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.pga.rule=Host(`pgaudit.${DOMAIN}`)
      - traefik.http.routers.pga.entrypoints=web

  pgaudit_conf:
    container_name: conf-pgaudit
    build:
      context: ../pgaudit-api
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    entrypoint: [php, app/ice, dbup, "--schema=[!tests]*"]
    restart: on-failure
