services:
  pgaudit:
    container_name: srv-pgaudit
    build:
      context: ../pgaudit-api
    volumes:
      - pub_key:/rsa/pub:ro
    environment:
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PATH_PUBLICKEY=${PUB_KEY}
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.pga.rule=Host(`pgaudit.${DOMAIN}`)
      - traefik.http.routers.pga.entrypoints=web

  pgaudit_conf:
    container_name: conf-pgaudit
    build:
      context: ../pgaudit-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PATH_PUBLICKEY=${PUB_KEY}
    entrypoint: [php, app/ice, dbup, "--schema={perfiles,[!t]*}"]
    restart: on-failure
