services:
  pqrs:
    container_name: srv-pqrs
    build:
      context: ../pqrs
    volumes:
      - type: volume
        source: keys
        volume:
          subpath: pub
        target: /rsa/pub
        read_only: true
    env_file: .env
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.pqr.rule=Host(`pqrs.localhost`)
      - traefik.http.routers.pqr.entrypoints=web

  pqrs_conf:
    container_name: conf-pqrs
    build:
      context: ../pqrs
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    entrypoint: [php, app/ice, dbup, "--schema=[!tests]*"]
    restart: on-failure
