services:
  webapp:
    container_name: srv-webapp
    build:
      context: ../webapp
      additional_contexts:
        - assets=https://github.com/marlonramirez/caresoft-assets.git
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.webapp.rule=Host(`localhost`)
      - traefik.http.routers.webapp.entrypoints=web 
