services:
  webapp:
    container_name: srv-webapp
    build:
      context: ../webapp
      additional_contexts:
        - assets=../_assets
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.webapp.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.webapp.entrypoints=web 
