include:
  - _services/infraestructure/traefik.yml
  - _services/infraestructure/database.yml
  - _services/infraestructure/rabbitmq.yml
  - _services/infraestructure/minio.yml
  - _services/application/jasper.yml
  - _services/application/pgadmin.yml
  - _services/application/n8n.yml
  - _services/domain/auth.yml
  - _services/domain/pqrs.yml
  - _services/domain/hiring.yml
  - _services/domain/pgaudit.yml
  - _services//domain/geo.yml
  - _services/domain/audit.yml
services:
  webapp:
    container_name: srv-webapp
    build:
      context: ./webapp
      additional_contexts:
        - assets=./_assets
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.webapp.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.webapp.entrypoints=web
