include:
  - _services/proxy.yml
  - _services/mq.yml
  - _services/database.yml
  - _services/auth.yml
  - _services/pqrs.yml
  - _services/hiring.yml
  - _services/pgaudit.yml
  - _services/audit.yml
  - _services/bi.yml
  - _services/tools.yml
services:
  webapp:
    container_name: srv-webapp
    build:
      context: ./webapp
      additional_contexts:
        - assets=./_assets
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.webapp.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.webapp.entrypoints=web
