services:
  geo:
    container_name: srv-geo
    build:
      context: ../../geo
    volumes:
      - pub_key:/rsa/pub:ro
      - ./logs:/app/app/storage/logs
    environment:
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PATH_PUBLICKEY=${PUB_KEY}
      - MQ_USER=${MQ_USER}
      - MQ_PASSWORD=${MQ_PASSWORD}
      - MQ_HOST=${MQ_HOST}
      - MQ_PORT=${MQ_PORT}
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.geo.rule=Host(`geo.${DOMAIN}`)
      - traefik.http.routers.geo.entrypoints=web

  geo_conf:
    container_name: conf-geo
    build:
      context: ../../geo
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PATH_PUBLICKEY=${PUB_KEY}
    entrypoint: /bin/bash
    command:
      - -c 
      - |
        set -e
        php app/ice dbup --schema=[!t]*
    restart: on-failure
