services:
  hiring:
    container_name: srv-hiring
    build:
      context: ../../hiring
    volumes:
      - pub_key:/rsa/pub:ro
      - ./logs:/app/app/storage/logs
    environment:
      - APP_URL=${PROTOCOL}://${DOMAIN}
      - APP_NAME=${APP_NAME}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PATH_PUBLICKEY=${PUB_KEY}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_KEY}
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.hiring.rule=Host(`hiring.${DOMAIN}`)
      - traefik.http.routers.hiring.entrypoints=web

  hiring_conf:
    container_name: conf-hiring
    build:
      context: ../../hiring
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PATH_PUBLICKEY=${PUB_KEY}
    entrypoint: /bin/bash
    command:
      - -c
      - php app/ice dbup --schema=[!t]*
    restart: on-failure
