services:
  pqrs:
    container_name: srv-pqrs
    build:
      context: ../../pqrs
    volumes:
      - pub_key:/rsa/pub:ro
      - ./logs:/app/app/storage/logs
    environment:
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PATH_PUBLICKEY=${PUB_KEY}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_KEY}
      - URL_DOCUMENT=http://audit/api/auth/
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.pqr.rule=Host(`pqrs.${DOMAIN}`)
      - traefik.http.routers.pqr.entrypoints=web

  pqrs_conf:
    container_name: conf-pqrs
    build:
      context: ../../pqrs
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PATH_PUBLICKEY=${PUB_KEY}
    entrypoint: /bin/bash
    command:
      - -c
      - |
        set -e
        php app/ice dbup --schema=[!t]*
    restart: on-failure
